version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.16.0

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys: - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          command: yarn install --frozen-lockfile

      - save_cache:
          keys: - yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
